linters:
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    enabled: false
  Comment:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  VendorPrefix:
    enabled: false
  IdSelector:
    enabled: false
  UrlFormat:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  HexLength:
    enabled: false
